server:
  port: 8081

spring:
  r2dbc:
    url: 'r2dbc:postgresql://postgres@localhost:5445/carpark'
    password: 'postgres'
  data:
    redis:
      host: 'localhost'
      port: 6379


one-map-sg:
  url: 'https://www.onemap.gov.sg/api/common/convert/3414to4326'
  token: ${ONEMAP_SG_TOKEN}

sg-park:
  url: 'https://api.data.gov.sg/v1/transport/carpark-availability'

coordinate:
  collection-key: 'coordinates'
  radius-in-km: 1.0